In [1]:
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],# thirty is not in numeric
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')  # Convert values to NaN

print(df)


   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [2]:
#Explanation: Missing values are filled with the column mean.
import pandas as pd

data = {'A': [1, 2, None],
        'B': [4, None, 6]}

df = pd.DataFrame(data)
df.fillna(df.mean(), inplace=True)  # give inplace=True 

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [3]:
#ans
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  # Reshape X into 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[4]]))# user input


[8.]


In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])  # Convert to 2D array

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [6]:
#Labels must be 0 and 1 for classification.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]  # Convert labels to numeric

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[1, 5]]))


[1]


In [7]:
#ans -Explanation: Convert categorical data into binary columns.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder(sparse=False)
encoded = encoder.fit_transform(df[['Category']])  # Convert to 2D

print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [8]:
#6.ans-No error, and correctly split data.

#Explanation: X and y must have the same number of samples.


from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  # Now y has the correct length

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train:", X_train)
print("y_train:", y_train)


X_train: [[1, 2], [5, 6], [3, 4]]
y_train: [0, 0, 1]


In [9]:
#ans A numerical prediction like [1] or [0].
#Explanation: Logistic Regression requires numeric labels, so we use LabelEncoder().
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)  # Convert labels to numeric

model = LogisticRegression()
model.fit(X_train, y_train_encoded)

print(model.predict([[2, 3]]))


[1]


In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

# Handling missing values by replacing NaN with the column mean
imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)

# Train the model
model = LinearRegression()
model.fit(X_train_imputed, y_train)

# Make a prediction
prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)


Predicted Output: [20.]


from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)  # Convert to numbers

model.fit(X_train, y_train_encoded)
print(model.predict([[2, 3]]))  # Output: [0] or [1]


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform([[1, 150]])
print(model.predict(X_test_scaled))  # More reliable output
